services:
  - type: web
    name: calculadora-preco-3d
    runtime: php
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    healthCheckPath: /
    env: production
    envVars:
      - key: PHP_VERSION
        value: "8.1"
      - key: DOCUMENT_ROOT
        value: /opt/render/project/src
      - key: TZ
        value: America/Sao_Paulo
