services:
  - type: web
    name: calculadora-preco-3d
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: TZ
        value: "America/Sao_Paulo"
